# Generated by Django 3.0.4 on 2020-05-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
