# Generated by Django 3.0.4 on 2020-05-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_appointment_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight_in_pounds',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=5),
            preserve_default=False,
        ),
    ]
